version: '3.8'
services:
  gateway:
    build: gateway
    image: gateway
    container_name: gateway_container
    ports:
      - "8080:8080"
    depends_on:
      - server
      - db

  server:
    build: server
    image: server
    container_name: server_container
    ports:
      - "9090:9090"
    depends_on:
      - db

  db:
    image: postgres:13.7-alpine
    container_name: postgres_db
    ports:
      - "6541:5432"
    environment:
      - DB_NAME=shareit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - DB_HOST=localhost
      - DB_PORT=5432